<a href="https://colab.research.google.com/github/Narci62/Python-cours---DA/blob/main/exercice_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import random


In [43]:
x = np.array([
       [ 0, 13,  5],
       [ 5,  8,  2],
       [ 3,  7, 12],
       [ 2,  8,  0],
       [ 7,  4,  1]
])
x

array([[ 0, 13,  5],
       [ 5,  8,  2],
       [ 3,  7, 12],
       [ 2,  8,  0],
       [ 7,  4,  1]])

Combien de notes sont supérieur à 5 ?

In [44]:
sup_5 = np.sum(x>5)
sup_5

6

Quel est le nombre de notes supérieur à 8 pour chaque étudiants ?

In [14]:
y = np.sum(x>8,axis=1)
y

array([0, 1, 0, 1, 2])

Quel est le nombre d'élèves ayant au moins 2 notes supérieures à 8 ?

In [8]:
x

array([[ 7,  6,  7],
       [14,  5,  8],
       [ 5,  3,  1],
       [14,  2,  4],
       [ 5,  9, 11]])

In [18]:
y = np.sum(np.sum(x>8,axis=1)>=2)
y

1

Est-ce que tous les élèves ont une note supérieur à 3 ?

In [24]:
np.all(x>3)

False

Est-ce qu'il y au moins un élève ayant au moins une note supérieur à 12 ?

In [25]:
np.any(x>12)

True

Quelle est la moyenne en Math et Physique de la classe si on considère uniquement les 3 élèves dont les notes apparaissent en premier ?

In [26]:
x

array([[ 7,  6,  7],
       [14,  5,  8],
       [ 5,  3,  1],
       [14,  2,  4],
       [ 5,  9, 11]])

In [30]:
np.mean(x[0:3,0:2],axis=0)

array([8.66666667, 4.66666667])

Combien d'élèves ont au moins 2 notes supérieurs à la médiane des moyennes (élèves) de la classe ?

In [31]:
x

array([[ 7,  6,  7],
       [14,  5,  8],
       [ 5,  3,  1],
       [14,  2,  4],
       [ 5,  9, 11]])

In [38]:
moy = np.mean(x,axis=1)
moy


array([6.66666667, 9.        , 3.        , 6.66666667, 8.33333333])

In [39]:
med = np.median(moy)
med

6.666666666666667

In [51]:
a = np.sum(x>med, axis=1) 
a 

array([1, 1, 2, 1, 1])

In [52]:
b = np.sum(a>=2)
b

1

In [53]:
x


array([[ 0, 13,  5],
       [ 5,  8,  2],
       [ 3,  7, 12],
       [ 2,  8,  0],
       [ 7,  4,  1]])